# OpenAI Configuration
openai:
  embedding_model: "text-embedding-ada-002"
  model: "gpt-4o"
  api_key: "***"
  base_url: "***"

# GLM Configuration
glm:
  model: "glm-4-plus"
  api_key: "***"
  base_url: "https://open.bigmodel.cn/api/paas/v4"
  embedding_model: "embedding-3"

# Deepseek Configuration
deepseek:
  model: "deepseek-chat"
  api_key: "***"
  base_url: "https://api.deepseek.com"

# Google Configuration
google:
  model: "gemini-pro"
  api_key: "your_google_api_key"
  embedding_model: "embedding-001"

# Model Parameters
model_params:
  openai_embedding_dim: 1536
  glm_embedding_dim: 2048
  google_embedding_dim: 768
  max_token_size: 8192

# HiRAG Configuration
hirag:
  working_dir: "your_work_dir"
  enable_llm_cache: false
  enable_hierachical_mode: true
  embedding_batch_num: 6
  embedding_func_max_async: 8
  enable_naive_rag: true